apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: ""
  configManagementPlugins: ""
  dex.config: ""
  ga.anonymizeusers: "false"
  ga.trackingid: ""
  help.chatText: ""
  help.chatUrl: ""
  kustomize.buildOptions: ""
  repositories: ""
  repository.credentials: ""
  resource.exclusions: ""
  resource.inclusions: ""
  statusbadge.enabled: "false"
  url: https://sahar-argo.stacks.co.il
  users.anonymous.enabled: "false"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-19T10:19:23Z"
  labels:
    app.kubernetes.io/managed-by: example-argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: my-config
  namespace: argocd
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ArgoCD
    name: example-argocd
    uid: 1b2fc82b-9648-4157-a790-7f9e7811852b
  resourceVersion: "234381"
  uid: df83eccc-5589-4afb-bb3d-59e741216939
