apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend 
  name: backend
  namespace: python-app
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: sahar2339/example-python-app:v1
        name: backend
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 600M
          requests:
            cpu: 100m
            memory: 300M
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
